In [1]:
import numpy as np

# 기본 구현
np.random.seed(0)  # 시드 고정
rewards = []

for n in range(1, 11):  # 10번 플레이
    reward = np.random.rand()  # 보상(무작위수로 시뮬레이션)
    rewards.append(reward)
    Q = sum(rewards) / n
    print(f'{n}번 플레이, 행동 가치 {Q}')

1번 플레이, 행동 가치 0.5488135039273248
2번 플레이, 행동 가치 0.6320014351498722
3번 플레이, 행동 가치 0.6222554154571294
4번 플레이, 행동 가치 0.6029123573420713
5번 플레이, 행동 가치 0.567060845741438
6번 플레이, 행동 가치 0.5801997236289743
7번 플레이, 행동 가치 0.5598265075766483
8번 플레이, 행동 가치 0.6013198192273272
9번 플레이, 행동 가치 0.6415801460355164
10번 플레이, 행동 가치 0.6157662833145425


In [2]:
# 증분 구현
np.random.seed(0)
Q = 0

for n in range(1, 11):
    reward = np.random.rand()
    Q = Q + (reward - Q) / n  # [식 1.5]
    print(f'{n}번 플레이, 행동 가치 {Q}')


1번 플레이, 행동 가치 0.5488135039273248
2번 플레이, 행동 가치 0.6320014351498722
3번 플레이, 행동 가치 0.6222554154571294
4번 플레이, 행동 가치 0.6029123573420713
5번 플레이, 행동 가치 0.567060845741438
6번 플레이, 행동 가치 0.5801997236289743
7번 플레이, 행동 가치 0.5598265075766483
8번 플레이, 행동 가치 0.6013198192273272
9번 플레이, 행동 가치 0.6415801460355164
10번 플레이, 행동 가치 0.6157662833145425


In [ ]:
import numpy as np
import matplotlib.pyplot as plt


class Bandit:
    def __init__(self, arms=10):  # arms = 슬롯머신 대수
        self.rates = np.random.rand(arms)  # 슬롯머신 각각의 승률 설정(무작위)

    def play(self, arm):
        rate = self.rates[arm]
        # 무작위 수가 승률보다 크면 보상으로 코인 1개를 반환
        if rate > np.random.rand():
            return 1
        else:
            return 0



In [5]:
bandit = Bandit()

for i in range(3):
    print(bandit.play(0))

0
0
1


In [ ]:
bandit = Bandit()

Q = 0

for n in range(1, 11): # 10번 반복
    reward = bandit.play(0) # 0번째 슬롯머신 플레이
    Q += (reward - Q) / n # 가치 추정치 갱신
    print(Q)

1.0
1.0
1.0
1.0
1.0
0.8333333333333334
0.8571428571428572
0.875
0.8888888888888888
0.8999999999999999


In [12]:
bandit = Bandit()
NUM_SLOTS = 5 # 슬롯머신의 개수

Qs = np.zeros(NUM_SLOTS) # 각 슬롯머신의 가치 추정치
ns = np.zeros(NUM_SLOTS) # 각 슬롯머신의 플레이 횟수

for n in range(10):
    action = np.random.randint(0, NUM_SLOTS) # 임의의 슬롯머신 선택
    reward = bandit.play(action)

    ns[action] += 1 # action번째 슬롯머신을 플레이한 횟수를 증가시킴
    Qs[action] += (reward - Qs[action]) / ns[action]
    print(Qs)

[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0.]
[0.  0.  0.  0.5 0. ]
[0.         0.         0.         0.33333333 0.        ]
[0.         0.         0.         0.33333333 0.        ]
[0.         0.         0.         0.33333333 0.        ]
[0.         0.         0.         0.33333333 0.        ]
[0.         0.         0.         0.33333333 0.        ]
[0.         0.         0.         0.33333333 0.        ]


In [ ]:
class Agent:
    def __init__(self, epsilon, action_size=10):
        self.epsilon = epsilon  # 무작위로 행동할 확률(탐색 확률)
        self.Qs = np.zeros(action_size)
        self.ns = np.zeros(action_size)

    # 슬롯머신의 가치 추정
    def update(self, action, reward):
        self.ns[action] += 1
        self.Qs[action] += (reward - self.Qs[action]) / self.ns[action]

    # 행동 선택(ε-탐욕 정책)
    def get_action(self):
        if np.random.rand() < self.epsilon:
            return np.random.randint(0, len(self.Qs))  # 무작위 행동 선택
        return np.argmax(self.Qs)  # 탐욕 행동 선택